import { OnboardingStep } from "../onboarding.types";

export const ONBOARDING_DISCOVERY_STEPS: OnboardingStep[] = [
  {
    id: "welcome",
    type: "welcome",
    title: "Welcome",
    body: "Build a life of prayer, discipline, and purpose. One salah at a time.",
    continueLabel: "Get started",
    pastel: "white",
  },
  {
    id: "biggest-problem",
    type: "multi-choice",
    title: "What's your biggest problem?",
    layout: "list",
    optionSpacing: "relaxed",
    requiresSelection: true,
    options: [
      { id: "procrastination", label: "Procrastination" },
      { id: "missing-prayers", label: "Missing prayers" },
      { id: "motivation", label: "Lack of motivation" },
      { id: "laziness", label: "Laziness" },
    ],
  },
  {
    id: "becoming-person",
    type: "multi-choice",
    title: "Are you becoming the person you want to be?",
    layout: "list",
    optionSpacing: "relaxed",
    requiresSelection: true,
    options: [
      { id: "stuck", label: "I feel stuck" },
      { id: "change", label: "I need a change" },
      { id: "improve", label: "I want to improve" },
      { id: "proud", label: "I'm proud of my progress" },
    ],
  },
  {
    id: "proud-moment",
    type: "multi-choice",
    title: "When was the last time you felt proud of yourself?",
    layout: "list",
    optionSpacing: "relaxed",
    requiresSelection: true,
    options: [
      { id: "days", label: "A few days ago" },
      { id: "month", label: "A month ago" },
      { id: "week", label: "This week" },
      { id: "years", label: "Years ago" },
    ],
  },
  {
    id: "why-change",
    type: "multi-choice",
    title: "Why does change matter to you?",
    layout: "list",
    optionSpacing: "relaxed",
    requiresSelection: true,
    options: [
      { id: "muslim", label: "Become a better Muslim" },
      { id: "goals", label: "Reach my goals" },
      { id: "discipline", label: "Build discipline" },
      { id: "family", label: "Make my family proud" },
    ],
  },
  {
    id: "mercy",
    type: "message",
    title: "Allah's mercy is greater than your mistakes.",
    body: "No matter how many prayers you've missed, today is a chance to start again.",
    bodyReveal: "fade",
    pastel: "default",
  },
  {
    id: "future-self",
    type: "comparison",
    title: "Imagine yourself one year from now",
    comparisonRows: [
      { positive: "5 daily prayers", negative: "Feeling lost" },
      { positive: "Purposeful and disciplined", negative: "Starting over every Monday" },
      { positive: "Consistent habits", negative: "Inconsistent routines" },
    ],
    footer: "Small steps taken consistently can change a life.",
    pastel: "default",
  },
  {
    id: "prayer-consistency",
    type: "multi-choice",
    title: "How consistent are your prayers?",
    layout: "list",
    optionSpacing: "relaxed",
    requiresSelection: true,
    options: [
      { id: "rarely-miss", label: "I rarely miss" },
      { id: "fairly", label: "I'm fairly consistent" },
      { id: "struggle", label: "I struggle sometimes" },
      { id: "rarely", label: "I rarely pray" },
    ],
  },
  {
    id: "holding-back",
    type: "multi-choice",
    title: "What's the biggest thing holding you back?",
    layout: "list",
    optionSpacing: "relaxed",
    requiresSelection: true,
    options: [
      { id: "distractions", label: "Distractions" },
      { id: "no-time", label: "No time to pray" },
      { id: "laziness", label: "Laziness" },
      { id: "motivation", label: "No motivation" },
    ],
  },
  {
    id: "missed-per-day",
    type: "slider",
    title: "How many salah do you miss a day?",
    min: 0,
    max: 5,
    requiresSelection: true,
  },
  {
    id: "symptoms",
    type: "symptoms",
    title: "Symptoms",
    continueLabel: "Continue",
    pastel: "default",
  },
];
