import { OnboardingStep } from "../onboarding.types";

export const ONBOARDING_SETUP_STEPS: OnboardingStep[] = [
  {
    id: "proud-one-year",
    type: "multi-choice",
    title: "What would make you proud one year from now?",
    layout: "list",
    requiresSelection: true,
    options: [
      { id: "discipline", label: "Build discipline" },
      { id: "allah", label: "Strengthen my relationship with Allah" },
      { id: "five-salah", label: "Pray all 5 salah consistently" },
      { id: "goals", label: "Achieve my goals" },
    ],
  },
  {
    id: "want-change",
    type: "multi-choice",
    title: "How badly do you want to change?",
    layout: "list",
    requiresSelection: true,
    options: [
      { id: "cant-explain", label: "I can't explain how much" },
      { id: "more-than-ever", label: "More than ever" },
      { id: "ready", label: "I'm ready to change" },
    ],
  },
  {
    id: "name",
    type: "name",
    title: "What can we call you?",
    body: "We will use this to personalize your experience.",
    continueLabel: "Continue",
    requiresSelection: true,
    pastel: "default",
  },
  {
    id: "calculation",
    type: "calculation",
    title: "Building your plan",
    calculationDurationMs: 6000,
    calculationTasks: [
      "Configuring your goals",
      "Setting your mission",
      "Setting alarm tone",
      "Scheduling your alarm",
      "Setting up wake receipt",
    ],
    calculationQuotes: [
      {
        title: "Indeed, with hardship comes ease.",
        source: "Qur'an 94:6",
      },
      {
        title:
          "The most beloved of deeds to Allah are the most consistent of them, even if they are few.",
        source: "Sahih al-Bukhari 6464",
      },
      {
        title: "Allah does not burden a soul beyond that it can bear.",
        source: "Qur'an 2:286",
      },
    ],
    pastel: "default",
  },
  {
    id: "missed-stats",
    type: "missed-graph",
    continueLabel: "Continue",
    pastel: "default",
  },
  {
    id: "bad-news",
    type: "downtrend",
    title: "A few habits are holding you back",
    bullets: [
      "Inconsistent prayer habits",
      "Lack of structure",
      "Difficulty staying disciplined",
    ],
    continueLabel: "Continue",
  },
  {
    id: "urgency-hope-slides",
    type: "slideshow",
    slides: [
      {
        graphic: "domino",
        title: "One miss becomes many",
        body: "Skip once, and the next prayer gets easier to skip. The habit stacks against you.",
        pastel: "hardRed",
      },
      {
        graphic: "hourglass",
        title: "Waiting makes it worse",
        body: "Every delay widens the gap. What felt temporary quietly becomes your new normal.",
        pastel: "hardRed",
      },
      {
        graphic: "summit",
        title: "You can rebuild this",
        body: "A clear system turns intention into consistency, one salah at a time.",
        checks: [
          "Praying all 5 salah",
          "Better discipline",
          "More peace of mind",
          "Stronger connection with Allah",
        ],
        pastel: "deepBlue",
      },
    ],
    pastel: "hardRed",
  },
  {
    id: "miraj-welcome-slides",
    type: "slideshow",
    brandLabel: "Miraj",
    continueLabel: "Continue",
    contentPlacement: "center",
    slides: [
      {
        graphic: "welcomeMiraj",
        title: "Welcome to Miraj",
        body: "Your salah companion, built to help you pray with more presence.",
        pastel: "white",
      },
      {
        graphic: "welcomeAlarms",
        title: "Alarms that bring you back",
        body: "Prayer alarms and wake receipts help you show up for salah, even when mornings feel hard.",
        pastel: "white",
      },
      {
        graphic: "welcomeConsistency",
        title: "Stay consistent every day",
        body: "Build streaks, explore duas, and get gentle reminders that keep faith close.",
        pastel: "white",
      },
    ],
    pastel: "white",
  },
  {
    id: "streak",
    type: "streak",
    title: "Stay motivated with a consistent daily routine",
    body: "Build a streak, one day at a time.",
    continueLabel: "Continue",
    pastel: "white",
  },
  {
    id: "rating",
    type: "rating",
    title: "Give us a rating",
    body: "Miraj was designed for Muslims building better salah habits.",
    continueLabel: "Continue",
    pastel: "default",
  },
  {
    id: "choose-goals",
    type: "multi-choice",
    title: "Choose your goals",
    layout: "list",
    optionSpacing: "loose",
    selectionMode: "multi",
    requiresSelection: true,
    options: [
      { id: "five-daily", label: "Pray all 5 daily prayers" },
      { id: "discipline", label: "Build discipline" },
      { id: "quran", label: "Read Quran daily" },
      { id: "dhikr", label: "Remember Allah more" },
      { id: "tahajjud", label: "Wake for tahajjud" },
      { id: "charity", label: "Give charity regularly" },
      { id: "fasting", label: "Fast Mondays & Thursdays" },
    ],
  },
  {
    id: "commitment",
    type: "commitment",
    title: "Sign your commitment",
    body: "Sign to show up for salah.",
    continueLabel: "Hold to Lock In",
    pastel: "default",
  },
  {
    id: "prepaywall-typing",
    type: "prepaywall-typing",
    pastel: "default",
  },
  {
    id: "personalized-plan",
    type: "personalized-plan",
    title: "Your personalized plan is ready",
    continueLabel: "Start my plan",
    pastel: "default",
  },
];
